### ISSUE TITLE
Klassen- und ER-Diagramme aktuallisieren

### ISSUE THREAD

**Issue by ghost** [HAW-BAI4-SE2/UniKit#13]

**Comment by ghost** [comment]
Jana hat sich schon bereiterklärt die Diagramme zu aktualisieren ^^

**Comment by simpletom** [comment]
Die DB-Diagramme sind aktualisiert und gepushed. Fachliches Modell steht noch aus (siehe Commit)

**Comment by JanaWengenroth** [comment]
DB-Diagramm space_of_time in appointment umbenannt

**Comment by JanaWengenroth** [comment]
Komponenten-Diagramm fehlt als vpp, nur als png da, dafür Datenmodell doppelt

**Comment by simpletom** [comment]
Checke gerade alle alten Stände der .vpp Datei die ich finden kann.

**Comment by simpletom** [comment]
Schlechte Nachrichten: Ich bin durch alle Versionen der .vpp gegangen die ich auftreiben konnte (Rechner, Dropbox, Pub). Alle haben den gleichen Fehler oder noch gar kein Komponentendiagramm.
Falls Andi nicht lokal auf seinem Rechner noch eine Version hat (was unwahrscheinlich ist), muss es neu erstellt werden anhand des Bildes fürchte ich.
Sieht übrigens so aus, als wenn der Fehler an dem Abend geschehen ist wo wir das Datenbankschema entworfen haben, die Datei von dem Abend hat den Fehler auch schon.

**Comment by ghost** [comment]
Leider habe ich kein altes Diagramm auf dem Rechner...

**Comment by simpletom** [comment]
@JanaWengenroth: Mit welcher Version hast du die Diagramme erstellt? Visual Paradigm sagt mir, dass die Version zu hoch für mich ist. Gleichzeitg sagt der Updater, dass ich keine Lizenz für 12.1 oder 12.2 habe.
WTF?
