### ISSUE TITLE
Developer-Braches einrichten

### ISSUE THREAD

**Issue by ghost** [HAW-BAI4-SE2/UniKit#14]
http://stackoverflow.com/questions/1519006/how-do-you-create-a-remote-git-branch
- 2. Antwort mit 526 Bewertungen
- Name für den Branch: vorname_branch

**Comment by ghost** [comment]
Danach ändert ihr euren Remote-Branch (ab Schritt Switch/Checkout):
http://joelabrahamsson.com/remote-branches-with-tortoisegit/

**Comment by simpletom** [comment]
Done.
