### ISSUE TITLE
Weitere Testdaten für CompletedCourse

### ISSUE THREAD

**Issue by ghost** [HAW-BAI4-SE2/UniKit#21]

**Comment by MrTorgue** [comment]
Erste Testdaten liegen in der Datenbank.
Diese gelten für Student 2055120 mit den Modulen PT, DB und PM2.

**Comment by ghost** [comment]
Erste Testdaten liegen in der Datenbank.
Diese gelten für Student 2055120 mit den Modulen PT, DB und PM2.
