### ISSUE TITLE
Sprache auf Git

### ISSUE THREAD

**Issue by simpletom** [HAW-BAI4-SE2/UniKit#24]
Frage: Welche Sprache wollen nun auf Git verwenden? Soweit ich mich erinnere hatten wir uns am 03.10 auf Deutsch geeinigt, da wir uns bei den Issues etc. gut verstehen sollen.
Die bisherigen Commits von Andi sind auf Englisch, Jana hat keine gemacht und bei dem einen von Jonas könnten es beide Sprachen sein.
Englisch für die Commits und Rest auf Deutsch erscheint mir widersinnig.

**Comment by ghost** [comment]
Ich dachte, da die Commits sehr nah am Programmcode sind, diese auch auf englisch sein sollten. Außerdem war es bei mir etwas Gewohnheit :D

Das sind jetzt vielleicht keine richtigen Argumente, weshalb ich auch kein Problem hätte, die Commits auf deutsch zu machen. Jedoch sollten wir uns was das angeht auf jeden Fall abstimmen.

Das der Rest, im Gegensatz zu meinen bisherigen Commits, auf deutsch ist dient den besseren Verständnis (was bei Issues und der Wiki Priorität hat).

**Comment by ghost** [comment]
Wir haben uns nun darauf geeinigt, die Commits auf englisch zu machen. Die Wiki und die Issues bleiben weiterhin auf deutsch. #Closed
