### ISSUE TITLE
Schnittstellen erzeugen

### ISSUE THREAD

**Issue by ghost** [HAW-BAI4-SE2/UniKit#3]
[Schnittstellen.txt](https://github.com/HAW-BAI4-SE2/UniKit/files/7323/Schnittstellen.txt)

**Comment by MrTorgue** [comment]
ACHTUNG!
- In der Tabelle STUDENT_TO_TEAM besitzt das Attribut team_id den Datentyp INT... Muss natürlich STRING sein, wie in der anderen Tabelle auch.
- Die Tabelle STUDENT_TO_COURSE habe ich umbenannt zu COURSE_REGISTRATIONS, damit wir sie besser von der Relation zwischen Studenten und Kursen aus der Test-Datenbank unterscheiden können.
