### ISSUE TITLE
Nächstes Meeting

### ISSUE THREAD

**Issue by simpletom** [HAW-BAI4-SE2/UniKit#33]
Habe soeben meinen Dienstplan erhalten.Treffen am Mittwoch geht klar. Wurde sich schon auf eine Zeit geeinigt? Falls ja, ist diese mir entgangen.
RFC.

**Comment by ghost** [comment]
Dann machen wir nächsten Mittwoch fest, würde ich sagen.
Mein Vorschlag: 14 Uhr in der HAW (Cafeteria).

**Comment by JonesPButter** [comment]
läuft

**Comment by ghost** [comment]
Würde es euch auch 12 Uhr passen?
Abends gehe ich mit meiner WG essen und 14 Uhr könnte vielleicht doch knapp werden...

**Comment by simpletom** [comment]
Vollständig akzeptabel!

**Comment by JanaWengenroth** [comment]
alles klar, also 12

**Comment by ghost** [comment]
Jup. Bis morgen :)
