### ISSUE TITLE
Labels der Issues bearbeiten

### ISSUE THREAD

**Issue by ghost** [HAW-BAI4-SE2/UniKit#34]
Ich denke einige Labels werden wir nicht nutzen und andere werden vielleicht noch benötigt. Zum Beispiel würde ich ein Label für offene Diskussionen (ggf. mit Diskussionsteilnehmern) wichtig finden.
Ich mache mir dazu morgen nochmal Gedanken.

**Comment by ghost** [comment]
Mein Vorschlag:
- _Bug_: Fehler, die unbedingt zu beheben sind
- _Task_: Aufgaben, die zu erledigen sind, um den entsprechenden Meilenstein abzuschließen
- _Enhancement_: Aufgaben, die optional sind und nur zu einer Verbessung der Software beitragen
- _ToDiscuss_: Issues mit offenen Diskussionen (nach Abschluss der Diskussion würde das Label entfernt werden)
- _InProgress_: Issues, die zur Zeit bearbeitet werden (bei längerer Unterbrechung der Arbeit würde das Label entfernt werden)
- _HelpWanted_: Issues, bei denen der Assignee zusätzliche Hilfe benötigt (sobald sich ausreichend viele Entwickler zur Mithilfe gemeldet haben, würde das Label entfernt werden)

**Comment by simpletom** [comment]
Klingt gut, bin dafür. Auf jeden Fall sinnvoller als das was Git von sich aus anbietet.

**Comment by ghost** [comment]
Done.
