### ISSUE TITLE
Maximale Teilnehmerzahl für Kurse hinzufügen

### ISSUE THREAD

**Issue by ghost** [HAW-BAI4-SE2/UniKit#38]
Optionales Attribut, welches bei der Anmeldung in Phase 1 berücksichtigt wird.

**Comment by MrTorgue** [comment]
+ Berücksichtigung in der Methode getAvaiableCourses().

**Comment by ghost** [comment]
Anzeige in der Anmeldemaske, wie viele Teilnehmer bereits in dem Kurs angemeldet sind.

**Comment by ghost** [comment]
Auf Datenbank-Ebene abgeschlossen: https://github.com/HAW-BAI4-SE2/UniKit/commit/705dc86fe3173fc189c6165deedf69d8ad39f0da
