### ISSUE TITLE
Merging der Branches

### ISSUE THREAD

**Issue by ghost** [HAW-BAI4-SE2/UniKit#42]

**Comment by simpletom** [comment]
Aktueller Stand von meinem Branch:
Die Logik des Programms steht soweit, inkl. der Befehle zur Persistierung.
Die Konfiguration von Hibernate habe ich aufgrund von Zeitmangel leider nicht hinbekommen, in diesem Sinne konnte ich auch nicht testen, ob alles funktioniert.
Ferner war ich etwas verwirrt wo die ganzen Mapping und Configs von Hibernate eigentlich liegen sollen.
Wenn soweit alles mit dem Mergen klappt und die DB Konfiguration steht, kann ich Montag Abend nochmal über meinen Code gehen und die letzten (hoffentlich nicht vorhandenen) Inkonsistenzen bereinigen.

**Comment by ghost** [comment]
#helpwanted
Siehe E-Mail die ich euch geschickt habe.

**Comment by ghost** [comment]
PS: Um die Initialisierung der Datenbank müsst ihr euch erstmal nicht kümmern.
Nutzt einfach nur die Getter-Methoden der beiden Klassen haw_hamburg.database.implementations.DatabaseManager und unikit.database.implementations.DatabaseManager.

**Comment by simpletom** [comment]
Update: Sitze an der Anpassung des Branches an die neue Konfiguration.
Die neue Library scheint keine Funktionalität zum Speichern von Daten in der Datenbank zu haben wenn ich richtig liege.
Soll ich jetzt weiterhin den Hibernate Code verwenden?

**Comment by simpletom** [comment]
Update 2: Streicht das, war nur nicht in der Doku...

**Comment by simpletom** [comment]
[f5c09b2](https://github.com/HAW-BAI4-SE2/UniKit/commit/f5c09b23232fc306808efdf6785a12dfd5ed5d98)

Code wurde soweit angepasst. Hier eine Zusammenfassung:
- Die beiden drigend notwendigen hibernate-properties Dateien wurden bei keinem Branch gepushed. Das führt zu einer NullPointerException beim Konstruktoraufruf.
- Habe jetzt erstmal beide Dateien auf Basis dessen was Andi irgendwann mal im Master Branch hatte erstellt, somit gibt es immerhin keine NullPointerException beim Konstruktoraufruf mehr.
- Allerdings gibt es jetzt eine sobald der UnikitDatabaseManager alle registrierten Kurse anzeigen will. ich bin mir ziemlich sicher, dass ich die properties-Dateien falsch erstellt habe (wasn't my job anyway)
- Ich nicht weiss ob das Programm alles macht was es soll, da die Doku des UnikitDatabaseManagers nicht mehr Informationen enthält als was meine IDE mir gibt wenn ich einen Methodenaufruf schreibe. Somit konnte ich auch nicht per Trial&Error die richtigen Ergebnisse erzielen.
- Finally: UnikitDatabaseManager.getAllRegistrations liefert List, should be Collection.

Thx @MrTorgue: Sieht so aus, als wenn du dir die letzten Tage den Arsch aufgerissen hast.
Ich habe morgen bis 18 Uhr Zeit an dem Projekt was zu machen, wenn bis dahin die properties funktionieren und mir nicht mehr alles um die Ohren fliegt.

**Comment by ghost** [comment]
- Zu den Properties: Diese habe ich euch per E-Mail geschickt, da ich sie durch den Eintrag auf der gitignore nicht pushen konnte (bzw. sie sofort wieder gelöscht wurden).
- Für die Informationen beim Methodenaufruf, muss die Javadoc in den Bibliothekseinstellungen hinzugefügt werden. Die Bibliothek kümmert sich um sämtlichen lesenden und schreibenden Zugriff auf die Datenbank.
- In dem Controller 'Application' auf dem master-Branch ist ein Beispiel, wie die Bibliothek initialisiert wird.
- Ich bin (Lernende Agenten sei dank...) noch nicht weiter mit der Implementation der Bibliothek gekommen. Aktueller Stand: Der Teil für den Import-Daten funktioniert vollständig, der Teil für die internen Daten nur teilweise. Ihr könnte aber davon ausgehen, dass ich das bis heute Nachmittag fertig bekommen werde.

@tbednorz: Wie meinst du das? Ich hatte nicht vor, deine Arbeit irgendwie schlecht zu machen. Die Probleme, die zu dem allen geführt haben, liegen im gesamten Team. Wir MÜSSEN für den nächsten Release besser planen und auch während der Entwicklung testen. Nicht erst beim Mergen...
Ich war einfach in Panik, dass wir nichts vorzuzeigen haben am Dienstag. Deshalb wollte/musste ich jemanden finden, der mir hilft... Hättest du dich nicht bereit erklärt, hätte ich Jana oder Jonas auch nochmal fragen können...

**Comment by ghost** [comment]
Ich habe deinen Thomas' Branch nun auch in den master-Branch gemerged, was aber noch nicht bedeutet, dass wir fertig sind.

**Comment by ghost** [comment]
Die Bibliothek ist nun für Phase 1 fertig. Alle Methoden die mit Teams (Phase 2) zusammenhängen sind allerdings noch nicht implementiert.
- die jar-Datei liegt im master-Branch: https://github.com/HAW-BAI4-SE2/UniKit/blob/master/project/lib/haw-hamburg-0.3.2.jar
- die JavaDoc ist auf unserer Projektseite zu finden: http://haw-bai4-se2.github.io/UniKit/haw-hamburg/0.3.2/javadoc/index.html
