### ISSUE TITLE
Typänderungen in allen Klassen: Collection zu List

### ISSUE THREAD

**Issue by simpletom** [HAW-BAI4-SE2/UniKit#43]
Bisher hatten wir die Konvention, dass wir alle Arten von Listen über den Typ Collection ansprechen. Ein mögliches Problem hierbei ist, dass Collections keine Methode besitzen einzelne Elemente anzusprechen, sprich: keine get(index)-Methode (siehe <a href="http://docs.oracle.com/javase/7/docs/api/java/util/Collection.html">hier</a>).
Mein Vorschlag wäre, die Typen auf List zu ändern und im folgenden dieses auch für neue Datenstrukturen zu verwenden. Konkret haben wir kein Problem mit dem Typ Collection. Aber es erscheint mit potentiell problematisch.

Pros: Einzelne Elemente können per Index angesprochen werden
Kons: Mir fallen keine ein, bitte kommentieren!

PS: Selbstredent würden die Änderungen erst nach dem Mergen und der Vorführung des Prototypen durchgeführt werden, ich melde mich hierfür freiwillig.

**Comment by ghost** [comment]
An sich spricht nichts dagegen, dennoch denke ich, dass die get(index)-Methode keinen großen Mehrwert darstellen könnte. In der Regel sind die Ids von unseren Objekten auf Datenbank-Ebene nicht vollständig durchnummeriert. Wenn z.B. Objekte aus der Datenbank gelöscht werden entstehenen "Lücken" in der Durchnummerierung. Diese führen dazu, dass der Index in unserer java.util.List nicht gleich dem Index des Objektes ist...

**Comment by simpletom** [comment]
Dies betrifft nur die Fälle in denen die Liste eine 1-zu-1 Abbildung einer Datenbanktabelle darstellt und ohne weitere Prüfmechanismen auch so behandelt wird.

**Comment by ghost** [comment]
In welchen Fällen würde denn eine get(index)-Methode gebraucht werden?
Ich möchte nicht dagegen reden, aber mir fällt im Moment kein guter Anwendungszweck einer solchen Methode ein... Und solange/wenn sie nicht gebraucht wird, sollte diese meiner Meinung nach auch nicht verfügbar sein. Das Protokoll einer Klasse sollte ja immer kleinstmöglich gehalten werden.
