### ISSUE TITLE
Hibernate Mapping erstellen

### ISSUE THREAD

**Issue by ghost** [HAW-BAI4-SE2/UniKit#6]

**Comment by MrTorgue** [comment]
Jana kümmert sich morgen drauf.

**Comment by ghost** [comment]
Wegen den Zugangsdaten nochmal eine kleine Info: https://github.com/HAW-BAI4-SE2/UniKit/issues/32#issuecomment-146833301

**Comment by ghost** [comment]
Nach einem Gespräch mit Torben hat sich ein alternativer (auf den ersten Blick schönerer) Lösungsweg für das Mapping ergeben: http://www.tutorialspoint.com/hibernate/hibernate_annotations.htm
Falls jemand Lust hat, die Aufgabe zu übernehmen kann er/sie sich gerne in diesem Issue taggen ^^
