### ISSUE TITLE
Testdaten für Tabellen erstellen (externe Daten)

### ISSUE THREAD

**Issue by ghost** [HAW-BAI4-SE2/UniKit#8]

**Comment by ghost** [comment]
Die Testdaten für die externe Datenbank sind so gut wie fertig.
Ich muss nurnoch einige Dummywerte ersetzen.

**Comment by MrTorgue** [comment]
Verbleibende Dummys:
- course.minTeamSize
- course.maxTeamSize

**Comment by MrTorgue** [comment]
Außerdem sollte die Gruppengröße vielleicht auf 20 Teilnehmer runtergesetzt werden.
